# Generated by Django 4.1.5 on 2023-01-12 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='word',
            new_name='phrase',
        ),
    ]
