# Generated by Django 4.1.5 on 2023-01-12 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_word_topic_phrase'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Topic',
            new_name='ArticleTopic',
        ),
    ]
