# Generated by Django 3.2.16 on 2023-01-18 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_counter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articletopic',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='counter',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='phrase',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterField(
            model_name='articletopic',
            name='title',
            field=models.TextField(max_length=150),
        ),
    ]
