# Generated by Django 3.2.16 on 2023-01-18 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20230118_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='phrase',
            name='category',
            field=models.CharField(default='Technical Article', max_length=150),
        ),
    ]
