# Generated by Django 3.2.16 on 2023-01-18 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_phrase_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phrase',
            name='category',
            field=models.CharField(choices=[('Technical Article', 'Technical Article'), ('Documentation', 'Documentation'), ('Proposals', 'Proposals'), ('White Papers', 'White Papers'), ('Instruction Manuals', 'Instruction Manuals'), ('Essay', 'Essay'), ('Medical Technical Writing', 'Medical Technical Writing')], default='Technical Article', max_length=150),
        ),
    ]
